### ISSUE TITLE
List on Graylog Marketplace

### ISSUE THREAD

**Issue by lennartkoopmann** [bvargo/gtail#2]
We have launched the beta of the Graylog Marketplace: https://marketplace.graylog.org/

The Marketplace is the central directory of all Graylog add-ons and integrations, including GELF libraries.

You would help us a lot if you could submit your tool there. :)

**Comment by bvargo** [comment]
Hi, thanks for the comment, but I do not use this tool on a regular basis anymore. As a result, I would not notice if it broke, so I would rather not make a listing in the marketplace. If someone wants to fork the project and keep it updated, then please feel free to list the fork in the marketplace.

I will add a note to the README indicating that I am no longer actively developing the project.

Sorry!
